project:
  type: website
  output-dir: docs

execute:
  freeze: true

website:
  title: "Spil banko og travebanko"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: pages/banko_live.qmd
        text: "Play"
      - href: LICENSE.md
        text: License
      # - href: reference/index.html
      #   text: "Refeference"
